# Generated by Django 5.0.7 on 2024-08-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allnodes',
            name='request',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='request',
        ),
        migrations.RemoveField(
            model_name='finishedgoods',
            name='request',
        ),
        migrations.RemoveField(
            model_name='initialnodes',
            name='request',
        ),
        migrations.RemoveField(
            model_name='pathogentestingmethod',
            name='request',
        ),
        migrations.RemoveField(
            model_name='pathogentestingmethodfnodes',
            name='request',
        ),
        migrations.AlterField(
            model_name='allnodes',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
