"""
Django settings for sensdweb project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os,ctypes

from pathlib import Path

from dotenv import load_dotenv
from django.contrib import messages

try:
    import osgeo
    _osg = Path(osgeo.__file__).parent  # ...\site-packages\osgeo
    # make sure Windows can resolve dependent DLLs from this folder
    if hasattr(os, "add_dll_directory"):
        os.add_dll_directory(str(_osg))
    # set data dirs
    os.environ.setdefault("GDAL_DATA", str(_osg / "data"))
    os.environ.setdefault("PROJ_LIB",  str(_osg / "proj"))
    os.environ["PROJ_LIB"] = r"C:\Program Files\PostgreSQL\16\share\contrib\postgis-3.4\proj"
    # pick the installed GDAL dll (3.9/3.10/3.11 etc.)
    _dll = next(iter(sorted(_osg.glob("gdal*.dll"), reverse=True)), None)
    if _dll:
        # preload and tell Django exactly which one to use
        ctypes.CDLL(str(_dll))
        GDAL_LIBRARY_PATH = str(_dll)
except Exception as _e:
    print("GDAL bootstrap warning:", _e)
# --- end ---


load_dotenv()

AUTH_USER_MODEL = 'authentication.CustomUser'



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("base dir", BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)+-3_5&1x23bkhx#x86y-fqg^ay-iyskbs27n&a#=^9ht=huaz'

SALT_KEY = SECRET_KEY

# CRYPTOGRAPHY_KEY  = SECRET_KEY

# CRYPTOGRAPHY_KEY  = os.getenv("CRYPTOGRAPHY_KEY")
# CRYPTOGRAPHY_SALT = os.getenv('CRYPTOGRAPHY_SALT').encode() if os.getenv('CRYPTOGRAPHY_SALT') else None

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_cryptography",
    'sensd',
    'authentication', # login and registration
    'sensdrequests.apps.RequestsConfig',
    'isdrequests',
    'mapsapp', # Maps Handling
    'django.contrib.gis', # GIS support for maps
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sensdweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sensdweb.wsgi.application'


# Database // Connections for Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',   # name of the database used 'django.db.backends.nameofdatabasesystem(here postgresql)'
        'NAME': os.getenv('DB_NAME'),                   # need to provide database name
        'USER': os.getenv('DB_USER'),                   # need to provide username
        'PASSWORD': os.getenv('DB_USER_PASSWORD'),      # need to provide password
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'sensdweb/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_TAGS = {
   messages.ERROR: 'danger',
}

#email stuff
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#SSl settings
# ALLOWED_HOSTS = ['134.124.243.144']
ALLOWED_HOSTS = ['sensdweb.com', '127.0.0.1', 'localhost', '134.124.26.19']
# Redirect all traffic to HTTPS
SECURE_SSL_REDIRECT = True  # Forces HTTPS
SESSION_COOKIE_SECURE = True  # Ensures cookies are sent over HTTPS
CSRF_COOKIE_SECURE = True     # Ensures CSRF cookies are sent over HTTPS

# Trust the Nginx reverse proxy for HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



#GDAL Settings

GDAL_LIBRARY_PATH = r"C:\Users\dadir\AppData\Roaming\Python\Python312\site-packages\osgeo\gdal311.dll"


# # Optional: stronger default signer for your own signed values
# SIGNING_BACKEND = "django_cryptography.core.signing.TimestampSigner"


#Newly Added
# AUTHENTICATION_BACKENDS = [
#     # 'authentication.backends.CaseInsensitiveModelBackend',  # our backend first
#     'django.contrib.auth.backends.ModelBackend',
# ] 