# Generated by Django 4.2.23 on 2025-08-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='private_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='public_key',
            field=models.TextField(),
        ),
    ]
