# Generated by Django 4.2.23 on 2026-09-28 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=30, null=True)),
                ('address', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('city', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('state', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('postal_code', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True)),
                ('photo_data_url', encrypted_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
