# Generated by Django 4.2.23 on 2026-09-28 00:17

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensd', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True),
        ),
    ]
