# Generated by Django 4.2.23 on 2025-10-01 03:57

from django.db import migrations
import sensdweb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_allnodes_created_by_alter_allnodes_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnodes',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arc',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dynamicparameters',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finishedgoods',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initialnodes',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noderesult',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pathogentestingmethod',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pathogentestingmethodfnodes',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variableresult',
            name='is_deleted',
            field=sensdweb.fields.CoercedEncryptedBooleanField(default=False),
        ),
    ]
