# Generated by Django 4.2.23 on 2025-10-03 16:54

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_allnodes_is_deleted_alter_arc_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderesult',
            name='cumulative_cost',
            field=encrypted_fields.fields.EncryptedFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='noderesult',
            name='demand_rate',
            field=encrypted_fields.fields.EncryptedFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='noderesult',
            name='direct_cost',
            field=encrypted_fields.fields.EncryptedFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='noderesult',
            name='lead_time',
            field=encrypted_fields.fields.EncryptedFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='variableresult',
            name='value',
            field=encrypted_fields.fields.EncryptedFloatField(null=True),
        ),
    ]
