# Generated by Django 5.1.4 on 2025-04-30 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveALotStore',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='Save A Lot', max_length=100)),
                ('street', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SchnucksStore',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='Schnucks', max_length=100)),
                ('street', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WalmartStore',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='Walmart', max_length=100)),
                ('street', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WholeFoodsStore',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='Whole Foods', max_length=100)),
                ('street', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
