# Generated by Django 5.1.4 on 2025-06-27 13:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(choices=[('Walmart', 'Walmart'), ('Schnucks', 'Schnucks'), ('Save A Lot', 'Save A Lot'), ('Whole Foods', 'Whole Foods')], max_length=100)),
                ('street', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='SaveALotStore',
        ),
        migrations.DeleteModel(
            name='SchnucksStore',
        ),
        migrations.DeleteModel(
            name='WalmartStore',
        ),
        migrations.DeleteModel(
            name='WholeFoodsStore',
        ),
    ]
