# Generated by Django 5.1.4 on 2025-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0002_store_delete_savealotstore_delete_schnucksstore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='object_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
