# Generated by Django 5.1.4 on 2025-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0003_alter_store_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyMetric',
            fields=[
                ('fips', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('salmonella_rate', models.FloatField()),
                ('svi_score', models.FloatField()),
                ('food_insecurity', models.FloatField()),
            ],
        ),
    ]
