# Generated by Django 5.1.4 on 2025-07-18 20:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0004_countymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSISPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('est_number', models.CharField(max_length=50)),
                ('establishment_id', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('dbas', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
