# Generated by Django 4.2.23 on 2025-09-04 16:41

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0005_fsispoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='company',
            field=encrypted_fields.fields.EncryptedCharField(choices=[('Walmart', 'Walmart'), ('Schnucks', 'Schnucks'), ('Save A Lot', 'Save A Lot'), ('Whole Foods', 'Whole Foods')], max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=encrypted_fields.fields.EncryptedFloatField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=encrypted_fields.fields.EncryptedFloatField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='object_id',
            field=encrypted_fields.fields.EncryptedCharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='store',
            name='zip_code',
            field=encrypted_fields.fields.EncryptedCharField(max_length=20),
        ),
    ]
