# Generated by Django 4.2.23 on 2025-10-23 16:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0006_alter_store_city_alter_store_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyBivariate',
            fields=[
                ('geoid', encrypted_fields.fields.EncryptedCharField(max_length=20, primary_key=True, serialize=False)),
                ('geo_id', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('state', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=5, null=True)),
                ('county', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=5, null=True)),
                ('name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200, null=True)),
                ('lsad', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('state_name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('stusps', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=5, null=True)),
                ('county_name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200, null=True)),
                ('censusarea', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('objectid', encrypted_fields.fields.EncryptedIntegerField(blank=True, null=True)),
                ('statefp', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=5, null=True)),
                ('countyfp', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=5, null=True)),
                ('countyns', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True)),
                ('intptlat', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('intptlon', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('salmonella_rate', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('social_vulnerability', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('salmonella_class', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('svi_class', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('bivariate_class', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('overall_food_insecurity', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('child_food_insecurity', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('rpl_themes', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='FSISCoordinates',
            fields=[
                ('object_id', encrypted_fields.fields.EncryptedIntegerField(primary_key=True, serialize=False)),
                ('company', encrypted_fields.fields.EncryptedCharField(max_length=300)),
                ('est_number', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('establishment_id', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('street', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('city', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('state', encrypted_fields.fields.EncryptedCharField(max_length=10)),
                ('zip_code', encrypted_fields.fields.EncryptedCharField(max_length=20)),
                ('phone', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=30, null=True)),
                ('activities', encrypted_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('dbas', encrypted_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('county', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('latitude', encrypted_fields.fields.EncryptedFloatField()),
                ('longitude', encrypted_fields.fields.EncryptedFloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='USStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('state_fips', encrypted_fields.fields.EncryptedCharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='CountyMetric',
        ),
        migrations.DeleteModel(
            name='FSISPoint',
        ),
    ]
