# Generated by Django 4.2.23 on 2026-04-17 15:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapp', '0007_countybivariate_fsiscoordinates_usstates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowLineQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', encrypted_fields.fields.EncryptedIntegerField(unique=True)),
                ('product_type_i', encrypted_fields.fields.EncryptedCharField(max_length=50)),
                ('from_id', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('from_node', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('from_city_area', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200)),
                ('from_state', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=10)),
                ('from_latitude', encrypted_fields.fields.EncryptedFloatField()),
                ('from_longitude', encrypted_fields.fields.EncryptedFloatField()),
                ('product_type_j', encrypted_fields.fields.EncryptedCharField(max_length=50)),
                ('to_id', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('to_node', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('to_city_area', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200)),
                ('to_state', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=10)),
                ('to_latitude', encrypted_fields.fields.EncryptedFloatField()),
                ('to_longitude', encrypted_fields.fields.EncryptedFloatField()),
                ('quantity', encrypted_fields.fields.EncryptedFloatField()),
                ('orig_fid', encrypted_fields.fields.EncryptedIntegerField(blank=True, null=True)),
                ('shape_length', encrypted_fields.fields.EncryptedFloatField(blank=True, null=True)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='FlowWithQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', encrypted_fields.fields.EncryptedIntegerField(unique=True)),
                ('product_type_i', encrypted_fields.fields.EncryptedCharField(max_length=50)),
                ('from_id', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('from_node', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('from_city_area', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200)),
                ('from_state', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=10)),
                ('from_latitude', encrypted_fields.fields.EncryptedFloatField()),
                ('from_longitude', encrypted_fields.fields.EncryptedFloatField()),
                ('product_type_j', encrypted_fields.fields.EncryptedCharField(max_length=50)),
                ('to_id', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('to_node', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('to_city_area', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200)),
                ('to_state', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=10)),
                ('to_latitude', encrypted_fields.fields.EncryptedFloatField()),
                ('to_longitude', encrypted_fields.fields.EncryptedFloatField()),
                ('quantity', encrypted_fields.fields.EncryptedFloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedLayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('file_type', encrypted_fields.fields.EncryptedCharField(max_length=10)),
                ('layer_type', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('feature_count', encrypted_fields.fields.EncryptedIntegerField(default=0)),
                ('geojson_data', encrypted_fields.fields.EncryptedTextField()),
                ('uploaded_at', encrypted_fields.fields.EncryptedDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
