# Generated by Django 4.2.23 on 2026-09-14 04:45

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapsapp', '0008_flowlinequantity_flowwithquantity_uploadedlayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('original_filename', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('fields', encrypted_fields.fields.EncryptedTextField(blank=True, default='[]')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('geometry_type', models.CharField(blank=True, max_length=50)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', encrypted_fields.fields.EncryptedTextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mapsapp.uploadeddataset')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('salmonella_risk', 'Salmonella Risk'), ('bivariate', 'Bivariate Analysis'), ('local_moran', "Local Moran's I"), ('spatial_association', 'Spatial Association Analysis'), ('spatial_regression', 'Spatial Regression Analysis')], max_length=50)),
                ('parameters', encrypted_fields.fields.EncryptedTextField(blank=True, default='{}')),
                ('summary', encrypted_fields.fields.EncryptedTextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='mapsapp.uploadeddataset')),
            ],
        ),
    ]
