# Generated by Django 4.2.23 on 2025-08-28 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', encrypted_fields.fields.EncryptedCharField(default='Optimization Request', max_length=200)),
                ('original_filename', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('note', encrypted_fields.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SAVED', 'Saved'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='NEW', max_length=12)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='var_y',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('product_div', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('mode', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('value', encrypted_fields.fields.EncryptedIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_vars', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='var_x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('product_div', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('mode', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('quantity', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_vars', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_label', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('row_values', encrypted_fields.fields.EncryptedJSONField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('col_nodes', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_sources', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_processors', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_warehouses', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_retailers', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_foodbanks', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_markets', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_modes', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_products', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_check_sal', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('col_nocheck_sal', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='salmonella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('product', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('level', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salmonella_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='precedence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_in', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('product_out', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedence_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='objective_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective_value', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('total_transport_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('total_gap_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('total_excess_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('total_intransit_penalty', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('total_revenue', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='gap_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('market', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('gap', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='excess_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('market', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('excess', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excesses', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='diversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('product_div', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('mode', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('capacity', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('fixed_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('unit_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('lead_time', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversion_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('product', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('demand', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('gap_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='arcs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('product_div', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('mode', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('capacity', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('multiplier', encrypted_fields.fields.EncryptedFloatField(default=1.0)),
                ('fixed_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('unit_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('lead_time', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs3_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='arcs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('product_div', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('mode', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('capacity', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('multiplier', encrypted_fields.fields.EncryptedFloatField(default=1.0)),
                ('fixed_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('unit_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('lead_time', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs2_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='arcs1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('product_div', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('mode', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120)),
                ('capacity', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('multiplier', encrypted_fields.fields.EncryptedFloatField(default=1.0)),
                ('fixed_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('unit_cost', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('lead_time', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs1_rows', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
