# Generated by Django 4.2.23 on 2025-08-28 17:32

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isdrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='note',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', null=True),
        ),
    ]
