# Generated by Django 4.2.23 on 2025-08-29 17:09

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isdrequests', '0002_alter_request_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='col_nocheck_sal',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
