# Generated by Django 4.2.23 on 2025-09-04 16:41

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isdrequests', '0003_alter_sets_col_nocheck_sal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='col_check_sal',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
