# Generated by Django 4.2.23 on 2025-09-05 14:20

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isdrequests', '0004_alter_sets_col_check_sal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='col_foodbanks',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_markets',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_modes',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_nodes',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_processors',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_products',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_retailers',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_sources',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sets',
            name='col_warehouses',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
