# Generated by Django 4.2.23 on 2025-09-05 14:26

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isdrequests', '0005_alter_sets_col_foodbanks_alter_sets_col_markets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective_summary',
            name='objective_value',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='objective_summary',
            name='total_excess_cost',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='objective_summary',
            name='total_gap_cost',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='objective_summary',
            name='total_intransit_penalty',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='objective_summary',
            name='total_revenue',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='objective_summary',
            name='total_transport_cost',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='salmonella',
            name='level',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='NA', max_length=120),
        ),
    ]
