# Generated by Django 4.2.23 on 2025-11-17 19:19

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isdrequests', '0006_alter_objective_summary_objective_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective_summary',
            name='fixed_diversion_cost',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='objective_summary',
            name='total_profit',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='objective_summary',
            name='variable_diversion_cost',
            field=encrypted_fields.fields.EncryptedFloatField(default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='shelf_time_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('market', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('shelf_time', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_times', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='salmonella_node_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('value', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salmonella_nodes', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='salmonella_intransit_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_in', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('product_out', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('mode', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('value', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salmonella_intransit', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='price_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('market', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('price', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lead_time_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_in', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_i', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('product_out', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node_j', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('lead_time', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_times', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cumulative_flow_time_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('node', encrypted_fields.fields.EncryptedCharField(max_length=120)),
                ('flow_time', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_times', to='isdrequests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
